### ISSUE TITLE
Add shebang to update.sh

### ISSUE THREAD

**Issue by MooseV2** [moeenz/vscode-updater#1]
Because `update.sh` uses bash syntax, the first line should be:
```shell
#!/usr/bin/env bash
```
This will prevent errors when trying to run it from a shell such as [fish shell](http://fishshell.com). An alternative way to call the script is by explicitly invoking bash (ie `bash ./update.sh`), but the shebang should be used anyway.

**Comment by moeenz** [comment]
Thanks for noticing.
It is fixed now.
